[[tool.uv.index]]
url = "https://pypi.org/simple"
default = true

[tool.uv.workspace]
members = ["contact_lookup", "orchestrator", "restaurant_finder", "rizzcharts", "real_estate_agent"]

[tool.uv.sources]
a2ui = { path = "../../../a2a_agents/python/a2ui_extension" }

